/*
 * This source file was generated by the Gradle 'init' task
 */
package ctci;

import java.util.Map;
import java.io.Reader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;


import org.junit.BeforeClass;
import org.junit.Test;
import com.google.gson.*;

import ctci.str_1_1_DupSol1;
import ctci.str_1_1_DupSol2;

import static org.junit.Assert.*;

public class AppTest {
    public static Map<String, String> data;
    
    @BeforeClass public static void loadTestDataFile() throws IOException {
        Reader reader = Files.newBufferedReader(Paths.get("./src/test/java/ctci/1_1_TestData.json"));
        Gson gson = new Gson();
        data = gson.fromJson(reader, Map.class);
    }
    
    @Test public void str_1_1_UniqueCharsS1() {
        assertFalse(str_1_1_DupSol1.findIn(data.get("1_1_unique_chars")));
    }
    
    @Test public void str_1_1_DuplicateCharsS1() {
        assertTrue(str_1_1_DupSol1.findIn(data.get("1_1_duplicate_chars")));
    }

    @Test public void str_1_1_UniqueCharsS2() {
        assertFalse(str_1_1_DupSol2.findIn(data.get("1_1_unique_chars")));
    }
    
    @Test public void str_1_1_DuplicateCharsS2() {
        assertTrue(str_1_1_DupSol2.findIn(data.get("1_1_duplicate_chars")));
    }


}
